version: '3'
services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    environment:
      - LANGUAGE_MODEL
    volumes:
      - /home/wware/ai-tinkerers/ollama_data:/root/.ollama
      - ${OLLAMA_MODELS:-/home/wware/ai-tinkerers/models}:/models
    command: serve
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
  jupyter:
    image: jupyter/scipy-notebook:latest
    volumes:
      - .:/home/jovyan
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=123
      - LANGUAGE_MODEL
      - OLLAMA_HOST
    ports:
      - "8888:8888"
    depends_on:
      - ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/api/status?token=123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    command: [
      "sh",
      "-c",
      "pip install pytest ipytest ipynbname && start-notebook.sh"
    ]

volumes:
  ollama_data:
